### PR TITLE
Added @ng-idle/core

### PR DESCRIPTION
**Pull request by karel1980**
DO NOT MERGE.

As you can see in this PR I have tried adding @ng-idle/core. The component works when running npm start, but the build.prod goal errors out with the following errors.

It feels like there's something wrong with systemjs but I'm wondering if anyone here can help shed some light on the issue.

`[20:38:13] Error on dependency parsing for dist/tmp/app/app.module.js at file:///Users/karelvervaeke/work/misc/angular-seed/dist/tmp/app/app.module.js
	Loading dist/tmp/app/main.js
	(SystemJS) ENOENT: no such file or directory, open '/Users/karelvervaeke/work/misc/angular-seed/node_modules/@ng-idle/package.json'
	Error: ENOENT: no such file or directory, open '/Users/karelvervaeke/work/misc/angular-seed/node_modules/@ng-idle/package.json'
	Error loading /Users/karelvervaeke/work/misc/angular-seed/node_modules/@ng-idle/package.json
[20:38:13] 'build.prod' errored after 7.25 s
[20:38:13] Error in plugin 'run-sequence(build.bundles.app)'
Message:
    Error on dependency parsing for dist/tmp/app/app.module.js at file:///Users/karelvervaeke/work/misc/angular-seed/dist/tmp/app/app.module.js
	Loading dist/tmp/app/main.js
	(SystemJS) ENOENT: no such file or directory, open '/Users/karelvervaeke/work/misc/angular-seed/node_modules/@ng-idle/package.json'
	Error: ENOENT: no such file or directory, open '/Users/karelvervaeke/work/misc/angular-seed/node_modules/@ng-idle/package.json'
	Error loading /Users/karelvervaeke/work/misc/angular-seed/node_modules/@ng-idle/package.json
Details:
    originalErr: Error: ENOENT: no such file or directory, open '/Users/karelvervaeke/work/misc/angular-seed/node_modules/@ng-idle/package.json'
Stack:
Error on dependency parsing for dist/tmp/app/app.module.js at file:///Users/karelvervaeke/work/misc/angular-seed/dist/tmp/app/app.module.js
	Loading dist/tmp/app/main.js
	(SystemJS) ENOENT: no such file or directory, open '/Users/karelvervaeke/work/misc/angular-seed/node_modules/@ng-idle/package.json'
	Error: ENOENT: no such file or directory, open '/Users/karelvervaeke/work/misc/angular-seed/node_modules/@ng-idle/package.json'
	Error loading /Users/karelvervaeke/work/misc/angular-seed/node_modules/@ng-idle/package.json
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-seed@1.0.0 build.prod: `gulp build.prod --color --env-config prod --build-type prod`
npm ERR! Exit status 1
npm ERR! 
`

### CODE REVIEW

**Comment by karel1980** [comment]
To help rule out the possibility that there's just something wrong with @ng-idle/core:
Doing the same thing on a newly generated project with @angular/cli does not produce any errors with the 'start' or 'build' scripts.

**Comment by vyakymenko** [comment]
@karel1980 , why did you created this pull request? Or you have an issue with this dependency?

**Comment by karel1980** [comment]
@vyakymenko I reported it here because I didn't manage to add the dependency using straightforward steps. The same straightforward steps work for a project seeded with @angular/cli, so I figured it would be a benefit for this project if it also worked here using simple, straightforward steps.

I suggested earlier that it might be an error with SystemJS but I'm no longer sure of that: Adding ng-idle is very similar to other modules which *do* work. This raises the possibility that it's just an issue with the packaging of ng-idle. I'll report it there as well

**Comment by volpejoaquin** [comment]
Hi @karel1980 !

You need add:

_Code:_
```
SYSTEM_BUILDER_CONFIG.packageConfigPaths.push(join('node_modules', '@ng-idle', '*', 'package.json'));
```
_File:_
project.config.ts

I have multiple npm libraries created by my team with the scope `@ woopa` and adding that line of code I could solve the same error that you are having at this moment.

**Pull request closed without merging**
