### PR TITLE
Update typescript to 2.4.1

### PR DESCRIPTION
**Pull request by fisenkodv**

### CODE REVIEW

**Comment by mgechev** [comment]
The build is failing because of npm@5, I suppose.

**Comment by fisenkodv** [comment]
@mgechev, I agree, because **AppVeyor build succeeded** with **npm@3.10.8**

**Comment by patrickmichalina** [comment]
try reinstalling gulp-typescript?

**Comment by fisenkodv** [comment]
Just tried:
1. `rm -r node_modules`
2. `npm install`
3. `npm run build.dev`
4. `npm run build.prod`
Works fine w/o any error

`npm --version` returns **5.1.0**

**Pull request merged**
