### PR TITLE
Migration to Angular 6 #2261

### PR DESCRIPTION
**Pull request by vyakymenko**
Update:
* Packages update.
* Resolved issues with postinstall scripts.
* Application code update.
* Add RxJS 6 support.
* Unit tests hotfix.

### CODE REVIEW

**Comment by vyakymenko** [comment]
@mgechev , please resolve merge conflict for support RxJS 6.

Thanks!

**Comment by vyakymenko** [comment]
@mgechev , we can't merge it because of conflict with RxJS 5 dependency. Could you resolve conflict ?

**Comment by mgechev** [comment]
No conflicts but looks like the build is failing.

**Comment by vyakymenko** [comment]
For me it shows you hat conflict is in dependency

**Comment by vyakymenko** [comment]
@mgechev , all checks passed.

**Comment by mgechev** [comment]
@vyakymenko awesome job!

**Comment by vyakymenko** [comment]
Thank you @mgchev !

**Pull request merged**
