### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by fr-esco**

### CODE REVIEW

**Comment by fr-esco** [comment]
It looks like Travis build breaks with an error I solved by running a fresh npm installation.

I use Node.js v6.11.1 and npm v3.10.10 on Windows 10.

**Comment by mgechev** [comment]
@fr-esco thanks for the update. Yes, would you also commit the lock files (yarn and npm).

**Comment by fr-esco** [comment]
This time both break, because:
`E/direct - Error: Could not find update-config.json. Run 'webdriver-manager update' to download binaries.`

Does it mean that CI servers should run `npm run webdriver-update` at least once now, as per README.md?

**Comment by mgechev** [comment]
@fr-esco sounds like it. Would you add this in the travis and appveyor scripts?

**Comment by fr-esco** [comment]
Now there is an issue with `FirefoxDriver`.
Have you ever seen it?

**Comment by mgechev** [comment]
@fr-esco I remember there was an issue with the FF driver a few months back, probably it persists.

**Comment by fr-esco** [comment]
Since Firefox 56.0.1, Protractor 5.1.x works as expected.

**Comment by mgechev** [comment]
@fr-esco great job!

**Comment by siovene** [comment]
@mgechev too late now, but those commits should have been squashed... it's unsightly to see 6 consecutive commits that all say _fix protractor for firefox_...

**Pull request merged**
