### PR TITLE
Clean up

### PR DESCRIPTION
**Pull request by vyakymenko**
Update:
* Remove protractor deps.
* Yarn upgrade.
* Remove old protractor e2e specs.
* Readme update.
* Remove selenium web driver.

### CODE REVIEW

**Comment by ArnaudPel** [comment]
I'm looking for the reason(s) why protractor got removed, but can't seem to find anything in the issues or commit messages, can anyone shed light on that ? Thanks.

BTW, the readme is still mentioning 'End-to-end tests with Protractor'.

**Comment by ArnaudPel** [comment]
Ah ok it's because it's been replaced with cypress.

**Comment by mgechev** [comment]
Thanks for the reminder. Would you open a PR so we can get the readme updated?

**Comment by ArnaudPel** [comment]
Did a ctrl+f :)
https://github.com/mgechev/angular-seed/pull/2232

**Pull request merged**
