### PR TITLE
Fixed HttpClientModule import issue #2084

### PR DESCRIPTION
**Pull request by ahmadqarshi**
Fixed "SyntaxError: Unexpected token <" issue [#2084](https://github.com/mgechev/angular-seed/issues/2084) by adding the tslib into additionalPackages inside "tools/config/seed.config.ts" .

### CODE REVIEW

**Comment by mgechev** [comment]
Thanks for the PR!

**Comment by brian428** [comment]
Correct me if I'm wrong, but wouldn't this also require adding `"importHelpers": true` to `/src/client/tsconfig.json`?

**Comment by mgechev** [comment]
Eventually the bundles might be smaller if we require the helpers manually. Need to be tested for verification.

**Comment by brian428** [comment]
FYI, I just tried it and it shaved about 3% off the size of my `app.js`. Not a huge difference but it is a bit smaller.

**Comment by mgechev** [comment]
Thanks for giving it a try!

**Pull request merged**
