### PR TITLE
chore: drop deprecation warnings and deprecated apis

### PR DESCRIPTION
**Pull request by mgechev**

### CODE REVIEW

**Comment by gforceg** [comment]
Do these warnings mean the ProdConfig interface needs to be changed to look like this?
export interface EnvConfig {
  API?: string;
  BUILD_TYPE?: string;
}

**Comment by mgechev** [comment]
No, `ENV_CONFIG` is the configuration for the current environment. The build type (i.e. the property `BUILD_TYPE`) is independent from `ENV_CONFIG`. We can have production build with stating environment config, for instance.

**Comment by TheDonDope** [comment]
Hey Minko, do the `build.*` and `serve.*` scripts in the `package.json` also need an update now?
For example: https://github.com/mgechev/angular-seed/blob/master/package.json#L12 ?

**Comment by mgechev** [comment]
Yess, these script params are useless now. I'll drop them in the next commit.

**Comment by KANekT** [comment]
https://github.com/mgechev/angular-seed/blob/master/tools/env/dev.ts - you need update this

**Comment by mgechev** [comment]
No, `ENV` is different from `BUILD_TYPE`.

**Pull request merged**
