### PR TITLE
Postinstall script update

### PR DESCRIPTION
**Pull request by vyakymenko**
Since https://github.com/angular/angular/issues/9359 issue is resolved, we can remove unused postinstall task for rx.js bundle.

### CODE REVIEW

**Comment by vyakymenko** [comment]
@mgechev , can you take a look for this one?

**Comment by mgechev** [comment]
Yes, I will review & merge tomorrow.

**Comment by Karasuni** [comment]
This PR breaks the main application. (reported by @mindietea and @kurtdaveting)

```
Uncaught ReferenceError: require is not defined
    at Rx.ts:5
(anonymous) @ Rx.ts:5
(index):60 SyntaxError: Unexpected token <
    at eval (<anonymous>)
```

([screenshot](http://imgur.com/a/tcX55))

reverting back to the previous version does still give an error but allows the app to run but with the following error:

```
[23:36:06] Starting 'build.js.dev'...
C:/dev/angular-seed/node_modules/rxjs/Subject.d.ts(16,22): error TS2415: Class 'Subject<T>' incorrectly extends base class 'Observable<T>'.
  Types of property 'lift' are incompatible.
    Type '<R>(operator: Operator<T, R>) => Observable<T>' is not assignable to type '<R>(operator: Operator<T, R>) => Observable<R>'.
      Type 'Observable<T>' is not assignable to type 'Observable<R>'.
        Type 'T' is not assignable to type 'R'.
[23:36:10] TypeScript: 1 semantic error
[23:36:10] TypeScript: emit succeeded (with errors)
```

This could be related to rxjs (version 5.4.1)

**Comment by vyakymenko** [comment]
@Karasuni , clean install ?

**Pull request merged**
