### PR TITLE
Feature/#1614

### PR DESCRIPTION
**Pull request by brian428**
Applied the changes we discussed, with two additional tweaks:
- Had to update codelyzer because I was getting TemplateParser errors on Windows on beta.2. Also went ahead and updated compodoc since latest version has some useful improvements.
- I realized that I mixed up the task names in my original issue/question. I had meant to ask about doing a `clean.once` at the beginning of `build.dev` (not `build.serve`), to make sure things start off clean. I went ahead and did this, but if you see a problem with it, let me know.

### CODE REVIEW

**Comment by netstart** [comment]
I think need add angular2-dependencies-graph, because this https://github.com/compodoc/compodoc/issues/5

npm i angular2-dependencies-graph --save-dev

**Comment by brian428** [comment]
Hmm, odd...I didn't have to install anything else to be able to run compodoc.

**Comment by brian428** [comment]
Also not sure what's up with the Travis failure, which says @angular/tsc-wrapped can't be found during compile.ahead.prod. Is that a known issue?

**Comment by mgechev** [comment]
Should be fine after merged the latest master.

**Pull request merged**
