### PR TITLE
chore(build): provide docker support

### PR DESCRIPTION
**Pull request by TheDonDope**
# Provide docker deployment support for separate environments

As requested in #1422 this commit provides a basic setup for docker deployment.

## Prerequisites:
- Have `docker-engine` and `docker-compose` installed
- Have a fresh clone of the project
- Right after cloning (do not run `$ npm install`, it is not neccessary), `cd` into the folder and run one of the below listed deployments.

## How to run:

For development deployment (`$ npm start` in a docker container) run the following (it will use the `docker-compose.yml`):

```bash
$ docker-compose build
$ docker-compose up -d
```

Open browser at http://localhost:5555/

For production deployment (`$ npm run serve.prod` in a docker container) run the following (explicitly using the `docker-compose.production.yml`):

```bash
$ docker-compose -f docker-compose.production.yml build
$ docker-compose -f docker-compose.production.yml up -d
```

Open browser at http://localhost:5555/

//cc @sclausen @mgechev @ludohenin 

P.S.: It would be nice to maybe even provide a production deployment which builds the application via `$ npm run build.prod` and then serving the output in an nginx container. 
I am working on something like that over here: https://github.com/TheDonDope/crudular/pull/1
Maybe @vyakymenko has some experience on the nginx deployment part?

### CODE REVIEW

**Comment by Shyam-Chen** [comment]
Only one `Dockerfile` is needed

use `docker-compose exec app npm run <SCRIPTS>`

**Comment by sclausen** [comment]
@TheDonDope @mgechev When I started to work on a docker solution for our dev-system, one requirement was to comfortably link a nginx to the app, so the developers can route multiple microservices in our environment to it without manually installing an nginx on their dev system.
It would be so nice, if you consider adding such a feature, too.

**Comment by TheDonDope** [comment]
@Shyam-Chen: Yes, the bare minimum is a single `Dockerfile`. However the implementation in the PR provides the possibility do have specific setups per environment. For example, while the normal `$ docker-compose build && docker-compose up -d` executes a `$ npm start`, whereas `$ docker-compose -f docker-compose.production.yml [...]` executes a `$ npm run serve.prod`.

**Comment by TheDonDope** [comment]
@sclausen 
Tying in nginx is definitely a point i want to get into. 
To add onto the current implementation here, my idea is, to have a second docker container in the `docker-compose.production.yml`, which hosts the nginx server.

The basic idea is (for production deployment):
1. Start first container and execute `$ npm run build.prod`
2. Make sure that the compiled `/dist/prod` is mounted as a shared named volume, so that it is accessible to other containers
3. Start the second container and boot up nginx, while linking `/dist/prod` from the shared named volume via `volumes_from`.

Yet, there is still a bit of manual work to do here:
Since the `$ npm run build.prod` task takes some time to complete, a simple `depends_on` in the nginx container is not enough to handle startup order. This only guarantees, that the first container is started first, but it does not wait until completion before starting the second (the nginx) container.
So, what you would need to do is:

1. Start build.prod: `$ docker-compose -f docker-compose.production.yml build && docker-compose -f docker-compose.production.yml up -d dist-build`
2. Wait for the dist build to finish and having persisted/copied/linked/whatever the `/dist/prod` files
3. Boot up the nginx container: `$ docker-compose -f docker-compose.production.yml up -d nginx`

**Comment by TheDonDope** [comment]
I'll merge for now, as he current PR already provides the basic functionality. We can track the NGINX additions in another issue / PR.

**Comment by sclausen** [comment]
@TheDonDope here is our docker config

```
FROM          ubuntu:15.10
MAINTAINER    name <email>

ENV           DEBIAN_FRONTEND=noninteractive

COPY          nginx_signing.key .
RUN           echo "deb http://nginx.org/packages/mainline/ubuntu/ wily nginx" >> /etc/apt/sources.list \
              && apt-key add nginx_signing.key \
              && apt-get update -y \
              && apt-get install -y nginx

COPY          angular2-seed.conf /etc/nginx/conf.d/angular2-seed.conf
COPY          angular2-seed_server.crt /etc/nginx/
COPY          angular2-seed_server.pem /etc/nginx/

CMD           service nginx start && sleep infinity
```

and my docker-compose.yml

```
nginx:
  build: nginx
  ports:
    - 127.0.0.1:443:443
  extra_hosts:
    - microservice1:192.168.0.1
    - microservice2:192.168.0.2
  volumes_from:
    - angular2_seed

angular2_seed:
  build: .
  command:
    "$NPM_TASK"
  volumes:
    - ./src:/var/www/src:ro
    - ./node_modules:/var/www/node_modules:ro
    - ./test:/var/www/test

**Comment by TheDonDope** [comment]
@sclausen Thank you very much!

Can you share the contents of your `angular2-seed.conf` (Thats my other issue: actually deploying the `/dist/prod` to nginx with support for `PathLocationStrategy`, respectively HTML 5 Push State. Thanks in advance!

**Comment by Shyam-Chen** [comment]
My `Dockerfile`
https://github.com/Shyam-Chen/Angular-Starter-Kit/blob/master/Dockerfile

My `docker-compose.yml`
https://github.com/Shyam-Chen/Angular-Starter-Kit/blob/master/docker-compose.yml

**Comment by sclausen** [comment]
@TheDonDope sure, I will post it tomorrow.

**Comment by sclausen** [comment]
@TheDonDope here is our nginx conf
```
map $http_upgrade $connection_upgrade {
  default upgrade;
  ''      close;
}

server {

  listen              443 ssl http2;

  server_name         angular2-seed.local;
  ssl                 on;
  ssl_certificate     angular2-seed_server.crt;
  ssl_certificate_key angular2-seed_server.pem;

  ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";
  ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
  ssl_prefer_server_ciphers on;
  ssl_session_cache shared:SSL:10m;
  ssl_session_tickets off; # Requires nginx >= 1.5.9
  add_header Strict-Transport-Security "max-age=63072000; preload";
  add_header X-Frame-Options DENY;

  location /api/microservice1 {
    rewrite ^/api/microservice1/(.*)$ /$1 break;
    proxy_pass https://microservice1/;
    proxy_http_version 1.1;
    proxy_set_header X-Forwarded-For $remote_addr;
  }

  location / {
    root /var/www/dist/dev;
    try_files $uri /index.html;
    index index.html;
    gzip on;
    gzip_types text/css text/javascript application/x-javascript application/json;
  }
  
  location /node_modules {
    root /var/www;
    gzip on;
    gzip_types text/css text/javascript application/x-javascript application/json;
  }
}
```

**Comment by TheDonDope** [comment]
@sclausen Thank you so much for sharing!!!! :)

**Pull request merged**
