### PR TITLE
Add support of `Angular Language Service`, Dependencies update.

### PR DESCRIPTION
**Pull request by vyakymenko**
Update:
* Add support of `Angular Language Service`.
More details: https://angular.io/guide/language-service#angular-language-service
* Dependencies update.

### CODE REVIEW

**Comment by mgechev** [comment]
@vyakymenko lets update Angular to 5.0.0 as well.

**Comment by vyakymenko** [comment]
Sure, @mgechev , I had pushed new changes.

**Comment by vyakymenko** [comment]
Let me fix compiler issue.

**Comment by vyakymenko** [comment]
It look's like Angular team updated `@angular/compiler-cli` and remove `CodeGenerator, main, NgcCliOptions`. I think that need more time to look for new API with `@angular/compiler-cli/ngtools2`.

**Pull request closed without merging**
