### PR TITLE
Add initialize and finalize tasks to all builds

### PR DESCRIPTION
**Pull request by RoxKilly**
All build sequences now begin by running the "initialize" task, and
end by running the "finalize" task. Users now have a convenient way
to run a startup/shutdown script before/after all builds without having
to override the composite tasks in /tools/config/seed.config.json.

This should make upgrading simpler.

Rel: #1989

### CODE REVIEW

**Comment by mgechev** [comment]
I think the issue in AppVeyor is not cause by your PR and, in fact, is already resolved.

**Comment by RoxKilly** [comment]
I've added another commit to hopefully fix #1463, #1498, and #1892

**Comment by mgechev** [comment]
Would you rebase with master?

**Comment by RoxKilly** [comment]
That's not something I've ever done so I did some research around what it means to rebase and tried to guess at what you were asking me. I'm pasting the Bash log here so you can see whether that's what you wanted.
```
C:\...\angular-seed>git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean

C:\...\angular-seed>git rebase
First, rewinding head to replay your work on top of it...
Fast-forwarded master to refs/remotes/origin/master.

C:\...\angular-seed>git remote -v
origin  https://github.com/RoxKilly/angular-seed.git (fetch)
origin  https://github.com/RoxKilly/angular-seed.git (push)

C:\...\angular-seed>git remote add upstream https://github.com/mgechev/angular2-seed.git

C:\...\angular-seed>git remote -v
origin  https://github.com/RoxKilly/angular-seed.git (fetch)
origin  https://github.com/RoxKilly/angular-seed.git (push)
upstream        https://github.com/mgechev/angular2-seed.git (fetch)
upstream        https://github.com/mgechev/angular2-seed.git (push)

C:\...\angular-seed>git fetch upstream
remote: Counting objects: 7, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 7 (delta 4), reused 6 (delta 3), pack-reused 0
Unpacking objects: 100% (7/7), done.
From https://github.com/mgechev/angular2-seed
 * [new branch]      codelyzer-3     -> upstream/codelyzer-3
 * [new branch]      computed-config -> upstream/computed-config
 * [new branch]      gh-pages        -> upstream/gh-pages
 * [new branch]      lazy            -> upstream/lazy
 * [new branch]      master          -> upstream/master
 * [new branch]      multi-apps      -> upstream/multi-apps

C:\...\angular-seed>git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean

C:\...\angular-seed>git rebase upstream/master
First, rewinding head to replay your work on top of it...
Applying: Add initialize and finalize tasks to all builds
Applying: Ignore /node_modules
Applying: Reverting my last change
Applying: Revert "Add initialize and finalize tasks to all builds"
Applying: Add finalize task to all builds (2nd attempt)
Applying: Remove noop "interpolate" arg from lodash.template call

C:\...\angular-seed>git status
On branch master
Your branch and 'origin/master' have diverged,
and have 10 and 6 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)
nothing to commit, working tree clean

C:\...\angular-seed>git push origin master
Username for 'https://github.com': RoxKilly
Password for 'https://RoxKilly@github.com':
To https://github.com/RoxKilly/angular-seed.git
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'https://github.com/RoxKilly/angular-seed.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

C:\...\angular-seed>git pull
Merge made by the 'recursive' strategy.

C:\...\angular-seed>git status
On branch master
Your branch is ahead of 'origin/master' by 11 commits.
  (use "git push" to publish your local commits)
nothing to commit, working tree clean

C:\...\angular-seed>git push origin master
Username for 'https://github.com': RoxKilly
Password for 'https://RoxKilly@github.com':
Counting objects: 45, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (45/45), done.
Writing objects: 100% (45/45), 22.62 KiB | 0 bytes/s, done.
Total 45 (delta 30), reused 0 (delta 0)
remote: Resolving deltas: 100% (30/30), completed with 10 local objects.
To https://github.com/RoxKilly/angular-seed.git
   ea039e5..27746c2  master -> master
```

**Comment by mgechev** [comment]
It seems the build got broken:

```
TypeError: Cannot read property 'status' of null
    at eval (lodash.templateSources[34]:9:15)
    at DestroyableTransform._transform (/home/travis/build/mgechev/angular-seed/node_modules/gulp-template/index.js:21:40)
    at DestroyableTransform.Transform._read (/home/travis/build/mgechev/angular-seed/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Readable.read (/home/travis/build/mgechev/angular-seed/node_modules/readable-stream/lib/_stream_readable.js:365:10)
    at flow (/home/travis/build/mgechev/angular-seed/node_modules/readable-stream/lib/_stream_readable.js:739:34)
    at DestroyableTransform.<anonymous> (/home/travis/build/mgechev/angular-seed/node_modules/readable-stream/lib/_stream_readable.js:610:7)
    at emitNone (events.js:105:13)
    at DestroyableTransform.emit (events.js:207:7)
    at onwriteDrain (/home/travis/build/mgechev/angular-seed/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_writable.js:300:12)
    at afterWrite (/home/travis/build/mgechev/angular-seed/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_writable.js:288:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-seed@1.0.0 e2e.ci: `gulp build.prod.rollup.aot --color && gulp build.e2e --color && gulp e2e --color`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-seed@1.0.0 e2e.ci script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2017-06-30T06_36_05_252Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-seed@1.0.0 tests.all: `npm test && npm run e2e.ci`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-seed@1.0.0 tests.all script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2017-06-30T06_36_05_560Z-debug.log
The command "npm run tests.all" exited with 1.
```

**Comment by mgechev** [comment]
@RoxKilly can we close the PR or you're planning to work on it further?

**Comment by RoxKilly** [comment]
@mgechev let's close it please. I will start over with a fresh fork.

**Pull request closed without merging**
