### PR TITLE
Bug fix with rxjs 5.4.1

### PR DESCRIPTION
**Pull request by vyakymenko**
Per comment from @Karasuni,

```
[23:36:06] Starting 'build.js.dev'...
C:/dev/angular-seed/node_modules/rxjs/Subject.d.ts(16,22): error TS2415: Class 'Subject<T>' incorrectly extends base class 'Observable<T>'.
  Types of property 'lift' are incompatible.
    Type '<R>(operator: Operator<T, R>) => Observable<T>' is not assignable to type '<R>(operator: Operator<T, R>) => Observable<R>'.
      Type 'Observable<T>' is not assignable to type 'Observable<R>'.
        Type 'T' is not assignable to type 'R'.
[23:36:10] TypeScript: 1 semantic error
[23:36:10] TypeScript: emit succeeded (with errors)
```
And per error log from AppVeyor:

```
[03:25:03] Starting 'compile.ahead.prod'...
Error: Error at C:/projects/angular2-seed/node_modules/rxjs/Subject.d.ts:16:22: Class 'Subject<T>' incorrectly extends base class 'Observable<T>'.
  Types of property 'lift' are incompatible.
    Type '<R>(operator: Operator<T, R>) => Observable<T>' is not assignable to type '<R>(operator: Operator<T, R>) => Observable<R>'.
      Type 'Observable<T>' is not assignable to type 'Observable<R>'.
        Type 'T' is not assignable to type 'R'.
    at new UserError (C:\projects\tools\@angular\tsc-wrapped\src\tsc.ts:33:5)
    at check (C:\projects\tools\@angular\tsc-wrapped\src\tsc.ts:81:11)
    at Tsc.typeCheck (C:\projects\tools\@angular\tsc-wrapped\src\tsc.ts:168:5)
    at C:\projects\tools\@angular\tsc-wrapped\src\main.ts:143:11
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
Compilation failed
npm ERR! Windows_NT 6.3.9600
```

Update:
* Hotfix for rxjs 5.4.1
* Yarn lock update.
Note: Resolved in via typescript version: https://github.com/angular/angular/issues/17800

### CODE REVIEW

**Comment by mgechev** [comment]
I reverted the changes back. Would you also introduce the previous PR?

**Comment by Karasuni** [comment]
I noted two issues in my last comment (one on each of the latest two commits). This PR would fix one error that is currently on HEAD.

Before including the other change I'd run it locally. I currently don't have the resources though. I wonder what exactly caused it to fail on our machines but not on travis/appveyor.

**Comment by vyakymenko** [comment]
@mgechev , yeah sure. You mean [post install script](https://github.com/mgechev/angular-seed/pull/1985) change? 
@Karasuni , it's `typescript` module bug, please look at my link.

**Comment by mgechev** [comment]
@Karasuni here are more details https://github.com/Reactive-Extensions/RxJS/issues/1487

**Pull request merged**
