### PR TITLE
build: update to system 0.20

### LINKED ISSUE #1785: SystemJS 0.20 support
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**
I'm testing new version of SystemJs 0.20 and i have a lot of problem on my fork. Are you going to try your solution with SystemJs 0.20?

### PR DESCRIPTION
**Pull request by mgechev**
Fix #1785

### CODE REVIEW

**Comment by mgechev** [comment]
@patrickmichalina what changes you had to make in your custom fork after the upgrade?

**Comment by patrickmichalina** [comment]
Had to add this to the project.config in order for systemjs to get it working. Previously it worked without this entry. Obviously no fault of the seed, its a systemjs thing.

```js
{
  name: '@nguniversal/express-engine',
  path: 'node_modules/@nguniversal/express-engine',
  packageMeta: {
    defaultExtension: 'js'
  }
}
```

the import being used is:
 ```js
import { REQUEST } from '@nguniversal/express-engine/tokens';
```

**Comment by mgechev** [comment]
Waiting for @meriturva to confirm that this works for him before I merge.

**Comment by mgechev** [comment]
Okay, merging it. In case anyone experiences issues we can always revert it back.

**Comment by meriturva** [comment]
@mgechev sorry ... i'm tying to pass to systemjs 0.20 right now but big issue with: https://github.com/auth0/angular-jwt now. So i will send you feedback as soon as possible.

**Comment by patrickmichalina** [comment]
@meriturva is it not working on your setup with 0.20? I have it working with angular-jwt.

**Comment by meriturva** [comment]
@patrickmichalina could you please share your config? i had to back switch systemjs to 0.19 version for now!

**Comment by patrickmichalina** [comment]
```
let additionalPackages: ExtendPackages[] = [
      {
        name: 'angular2-jwt',
        path: 'node_modules/angular2-jwt/angular2-jwt.js'
      }, {
        name: 'js-cookie',
        path: 'node_modules/js-cookie/src/js.cookie.js'
      }, {
        name: '@nguniversal/express-engine',
        path: 'node_modules/@nguniversal/express-engine',
        packageMeta: {
          defaultExtension: 'js'
        }
      }];

    this.addPackagesBundles(additionalPackages);
```

**Comment by meriturva** [comment]
I have found that big problem is typescript with tsconfig `module: system` and `angular2-jwt` on our big project.
Really strange.

**Pull request merged**
