### PR TITLE
Exclude Cypress and Karma from docker images

### PR DESCRIPTION
**Pull request by ArnaudPel**
Currently, the test code installed in the docker containers cannot be used:
Eg. to run Karma, the command `npm test` would have to be run from inside the container. On top of not being documented in the readme, this would lead to major issues, eg. the absence of a browser. Generally speaking, AFAIK, handling GUI apps in Docker is far from trivial.

Therefore, there is no point in wasting time and bandwidth waiting for Cypress to install when building the images.

If this change is accepted, may I ask someone to help and have a look at what other dependencies could go into `optionalDependencies` ? Basically, every dependency only required in the test env can go there.

Thanks

### CODE REVIEW

**Comment by ArnaudPel** [comment]
Incidentally, this commit also fixes the production docker image build.
Until #2288 is fixed.

**Comment by mgechev** [comment]
The buld is still failing. Let's fix it before we merge.

**Comment by ArnaudPel** [comment]
Yes I'm a bit lost as to why Travis won't install Cypress, but seems to find Karma without any issue. I put both in the same `optionalDepedencies` section.

As can be seen in the following commits, I tried the following changes:
- don't put `cypress/` and `cypress.json` in `.dockerignore`  -- even though I see no mention of our docker config in `.travis.yml`
- move Cypress back to `devDependencies`

None of the above work. In want for something else to try, I'm tempted to revert all the changes on this branch to check that the Cypress install issue is indeed coming from my change.

The Appveyor build has all tests (Karma, Cypress) passing, but crashes right after Cypress completes :(

**Comment by ArnaudPel** [comment]
Ok I got yet another idea, try to revert `package-lock.json` to master.

**Comment by ArnaudPel** [comment]
Ok so that's what I was suspecting: even after reverting everything to master, I still get the same error:
`No version of Cypress is installed in: /home/travis/.cache/Cypress/3.0.1/Cypress`

I've never worked with Travis or any Github CI before, so I can't invest more effort into that sorry. All I can say is that the Appveyor build runs all tests successfully, even though it is not aware of it :)

**Comment by ArnaudPel** [comment]
Trying again in #2309

**Pull request closed without merging**
